#!/usr/bin/env ruby
#^syntax detection

# site 'http://community.opscode.com/api/v1'
git 'https://github.com/concord-consortium/chef-repo', :path => 'cookbooks'

cookbook 'apache2'
cookbook 'users',
    :git => 'https://github.com/opscode/cookbooks'
cookbook 'git'
cookbook 'nodejs',
    :git => 'https://github.com/mdxp/nodejs-cookbook'
cookbook 'npm',
    :git => 'http://github.com/balbeko/chef-npm/'
cookbook 'couchdb',
    :git => 'https://github.com/opscode/cookbooks'    

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
